name: bordered
description: Create variable-width, gradient-colored borders with adjustable chamfer depth and automatic animation.
version: 0.1.0
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/bordered

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  animated_value: ^0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
